export const LANGUAGES = [
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Korean",
  "Hindi",
  "Russian",
  "Portuguese",
  "Arabic",
  "Italian",
  "Turkish",
  "Dutch",
];
export const LANGUAGE_TO_FLAG = {
  english: "gb",
  spanish: "es",
  french: "fr",
  german: "de",
  mandarin: "cn",
  japanese: "jp",
  korean: "kr",
  hindi: "in",
  russian: "ru",
  portuguese: "pt",
  arabic: "sa",
  italian: "it",
  turkish: "tr",
  dutch: "nl",
};

export const GENDER_OPTIONS = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "other", label: "Other" },
  { value: "prefer-not-to-say", label: "Prefer not to say" },
];

export const INTEREST_TAGS = [
  "Music",
  "Movies",
  "Gaming",
  "Travel",
  "Books",
  "Sports",
  "Fitness",
  "Cooking",
  "Art",
  "Technology",
  "Photography",
  "Fashion",
  "Nature",
  "Anime",
  "Dancing",
  "Writing",
  "Business",
  "Science",
  "Spirituality",
  "Comedy",
];